src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $check_in_date;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $check_out_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Room", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $room_id;

    public function __construct()
    {
        $this->date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCheckInDate(): ?\DateTimeInterface
    {
        return $this->check_in_date;
    }

    public function setCheckInDate(\DateTimeInterface $check_in_date): self
    {
        $this->check_in_date = $check_in_date;

        return $this;
    }

    public function getCheckOutDate(): ?\DateTimeInterface
    {
        return $this->check_out_date;
    }

    public function setCheckOutDate(\DateTimeInterface $check_out_date): self
    {
        $this->check_out_date = $check_out_date;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getRoomId(): ?room
    {
        return $this->room_id;
    }

    public function setRoomId(room $room_id): self
    {
        $this->room_id = $room_id;

        return $this;
    }

    public function __ToString()
    {
        return (string) $this->getId();
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class BookingType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
        $builder
            ->add('check_in_date')
            ->add('check_out_date')
            ->add('user_id')
            ->add('room_id')
        ;
        } else {
            $builder
            ->add('check_in_date')
            ->add('check_out_date')
        ;
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/booking")
 */
class BookingController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="booking_index", methods={"GET"})
     */
    public function index(BookingRepository $bookingRepository): Response
    {   
        if ($this->security->isGranted('ROLE_ADMIN')){
            return $this->render('booking/index.html.twig', [
                'bookings' => $bookingRepository->findAll(),
            ]);
        } elseif($this->security->isGranted('ROLE_CUSTOMER')) {
            $user = $this->getUser()->getId();
            return $this->render('booking/index.html.twig', [
                'bookings' => $bookingRepository->findBy(['user_id' => $user]),
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/new", name="booking_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($booking);
            $entityManager->flush();

            return $this->redirectToRoute('booking_index');
        }

        return $this->render('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form->createView(),
        ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}", name="booking_show", methods={"GET"})
     */
    public function show(Booking $booking): Response
    {
        if($this->security->isGranted('ROLE_ADMIN')){
            return $this->render('booking/show.html.twig', [
                'booking' => $booking,
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}/edit", name="booking_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Booking $booking): Response
    {
        if($this->security->isGranted('ROLE_ADMIN')){
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('booking_index', [
                'id' => $booking->getId(),
            ]);
        }

        return $this->render('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form->createView(),
        ]);

        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}", name="booking_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Booking $booking): Response
    {
        if($this->security->isGranted('ROLE_ADMIN')){
            if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($booking);
                $entityManager->flush();
            }
        return $this->redirectToRoute('booking_index');
        } else {
            return $this->redirectToRoute('default');
        }
    }

}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('booking/_form.html.twig', {'button_label': 'Update'}) }}
    <div style="display: flex">
    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('booking_index') }}">back to list</a>
    {{ include('booking/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bookings{% endblock %}

{% block body %}
    <h1>Bookings</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Check_in_date</th>
                <th>Check_out_date</th>
                {% if is_granted("ROLE_ADMIN")%}
                <th>actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.date ? booking.date|date('Y-m-d') : '' }}</td>
                <td>{{ booking.checkInDate ? booking.checkInDate|date('Y-m-d H:i:s T') : '' }}</td>
                <td>{{ booking.checkOutDate ? booking.checkOutDate|date('Y-m-d H:i:s T') : '' }}</td>
                {% if is_granted("ROLE_ADMIN")%}
                <td>
                    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('booking_show', {'id': booking.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN")%}
    <a class="btn btn-success" href="{{ path('booking_new') }}">Create new</a>
    {% endif %}
    {% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Booking{% endblock %}

{% block body %}
    <h1>Create new Booking</h1>
    {{ include('booking/_form.html.twig') }}
    <a class="btn btn-primary" href="{{ path('booking_index') }}">back to list</a>
    
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ booking.date ? booking.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Check_in_date</th>
                <td>{{ booking.checkInDate ? booking.checkInDate|date('Y-m-d H:i:s T') : '' }}</td>
            </tr>
            <tr>
                <th>Check_out_date</th>
                <td>{{ booking.checkOutDate ? booking.checkOutDate|date('Y-m-d H:i:s T') : '' }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN")%}
    <div style="display: flex">
    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('booking_index') }}">back to list</a>

    <a style="margin-right: 10px" class="btn btn-secondary" href="{{ path('booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
    </div>
    {% endif %}    
{% endblock %}