src/Entity/Payment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PaymentRepository")
 */
class Payment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bank_details;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $card_details;

    /**
     * @ORM\Column(type="date")
     */
    private $date_payment_due;

    /**
     * @ORM\Column(type="date")
     */
    private $date_payment_made;

    /**
     * @ORM\Column(type="float")
     */
    private $amount_paid;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Paymentmethod")
     * @ORM\JoinColumn(nullable=false)
     */
    private $paymentmethod_id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Booking", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $booking_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBankDetails(): ?string
    {
        return $this->bank_details;
    }

    public function setBankDetails(string $bank_details): self
    {
        $this->bank_details = $bank_details;

        return $this;
    }

    public function getCardDetails(): ?string
    {
        return $this->card_details;
    }

    public function setCardDetails(string $card_details): self
    {
        $this->card_details = $card_details;

        return $this;
    }

    public function getDatePaymentDue(): ?\DateTimeInterface
    {
        return $this->date_payment_due;
    }

    public function setDatePaymentDue(\DateTimeInterface $date_payment_due): self
    {
        $this->date_payment_due = $date_payment_due;

        return $this;
    }

    public function getDatePaymentMade(): ?\DateTimeInterface
    {
        return $this->date_payment_made;
    }

    public function setDatePaymentMade(\DateTimeInterface $date_payment_made): self
    {
        $this->date_payment_made = $date_payment_made;

        return $this;
    }

    public function getAmountPaid(): ?float
    {
        return $this->amount_paid;
    }

    public function setAmountPaid(float $amount_paid): self
    {
        $this->amount_paid = $amount_paid;

        return $this;
    }

    public function getPaymentmethodId(): ?paymentmethod
    {
        return $this->paymentmethod_id;
    }

    public function setPaymentmethodId(?paymentmethod $paymentmethod_id): self
    {
        $this->paymentmethod_id = $paymentmethod_id;

        return $this;
    }

    public function getBookingId(): ?booking
    {
        return $this->booking_id;
    }

    public function setBookingId(booking $booking_id): self
    {
        $this->booking_id = $booking_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/PaymentType.php
<?php

namespace App\Form;

use App\Entity\Payment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaymentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('bank_details')
            ->add('card_details')
            ->add('date_payment_due')
            ->add('date_payment_made')
            ->add('amount_paid')
            ->add('paymentmethod_id')
            ->add('booking_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Payment::class,
        ]);
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Payment;
use App\Form\PaymentType;
use App\Repository\PaymentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/payment")
 */
class PaymentController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="payment_index", methods={"GET"})
     */
    public function index(PaymentRepository $paymentRepository): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
            return $this->render('payment/index.html.twig', [
                'payments' => $paymentRepository->findAll(),
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/new", name="payment_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
            $payment = new Payment();
            $form = $this->createForm(PaymentType::class, $payment);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($payment);
                $entityManager->flush();

                return $this->redirectToRoute('payment_index');
            }

            return $this->render('payment/new.html.twig', [
                'payment' => $payment,
                'form' => $form->createView(),
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}", name="payment_show", methods={"GET"})
     */
    public function show(Payment $payment): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
            return $this->render('payment/show.html.twig', [
                'payment' => $payment,
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}/edit", name="payment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Payment $payment): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
            $form = $this->createForm(PaymentType::class, $payment);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('payment_index', [
                    'id' => $payment->getId(),
                ]);
            }

            return $this->render('payment/edit.html.twig', [
                'payment' => $payment,
                'form' => $form->createView(),
            ]);
        } else {
            return $this->redirectToRoute('default');
        }
    }

    /**
     * @Route("/{id}", name="payment_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Payment $payment): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')){
            if ($this->isCsrfTokenValid('delete'.$payment->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($payment);
                $entityManager->flush();
            }

        return $this->redirectToRoute('payment_index');
        } else {
            return $this->redirectToRoute('default');
        }
    }
}

templates/payment/_delete_form.html.twig
<form method="post" action="{{ path('payment_delete', {'id': payment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ payment.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/payment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button style="float: left; margin-right: 10px;" class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/payment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Payment{% endblock %}

{% block body %}
    <h1>Edit Payment</h1>

    {{ include('payment/_form.html.twig', {'button_label': 'Update'}) }}
    <div style="display: flex">
    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('payment_index') }}">back to list</a>
    {{ include('payment/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/payment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payments{% endblock %}

{% block body %}
    <h1>Payments</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Bank_details</th>
                <th>Card_details</th>
                <th>Date_payment_due</th>
                <th>Date_payment_made</th>
                <th>Amount_paid</th>
                {% if is_granted("ROLE_ADMIN")%}
                <th>actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
            <tr>
                <td>{{ payment.id }}</td>
                <td>{{ payment.name }}</td>
                <td>{{ payment.bankDetails }}</td>
                <td>{{ payment.cardDetails }}</td>
                <td>{{ payment.datePaymentDue ? payment.datePaymentDue|date('Y-m-d') : '' }}</td>
                <td>{{ payment.datePaymentMade ? payment.datePaymentMade|date('Y-m-d') : '' }}</td>
                <td>{{ payment.amountPaid }}</td>
                {% if is_granted("ROLE_ADMIN")%}
                <td>
                    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('payment_show', {'id': payment.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('payment_edit', {'id': payment.id}) }}">edit</a>
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN")%}
    <a class="btn btn-success" href="{{ path('payment_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/payment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Payment{% endblock %}

{% block body %}
    <h1>Create new Payment</h1>

    {{ include('payment/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('payment_index') }}">back to list</a>
{% endblock %}

templates/payment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payment{% endblock %}

{% block body %}
    <h1>Payment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ payment.id }}</td>
            </tr>
            <tr>
                <th>Bank_details</th>
                <td>{{ payment.bankDetails }}</td>
            </tr>
            <tr>
                <th>Card_details</th>
                <td>{{ payment.cardDetails }}</td>
            </tr>
            <tr>
                <th>Date_payment_due</th>
                <td>{{ payment.datePaymentDue ? payment.datePaymentDue|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_payment_made</th>
                <td>{{ payment.datePaymentMade ? payment.datePaymentMade|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Amount_paid</th>
                <td>{{ payment.amountPaid }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN")%}
    <div style="display: flex">
    <a style="margin-right: 10px" class="btn btn-primary" href="{{ path('payment_index') }}">back to list</a>

    <a style="margin-right: 10px" class="btn btn-secondary" href="{{ path('payment_edit', {'id': payment.id}) }}">edit</a>

    {{ include('payment/_delete_form.html.twig') }}
    </div>
    {% endif %}
{% endblock %}